name: Backend CI

on:
  push:
    branches: [ back ]
  pull_request:
    branches: [ back ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: 'Docker build'
      run: docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend-Hive:${{ github.sha }} .
    - name: 'Docker push'
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend-Hive:${{ github.sha }}
