name: Frontend CI

on:
  push:
    branches: [ front ]
  pull_request:
    branches: [ front ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Docker login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: 'Docker build'
      run: docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontendhive:${{ github.sha }} .
    - name: 'Docker push'
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontendhive:${{ github.sha }}
